# Generated by Django 6.1 on 2026-09-12 15:03

from django.db import migrations, models


def copiar_tag_para_tags(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    for note in Note.objects.all():
        if getattr(note, 'tag_id', None):
            note.tags.add(note.tag_id)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_tag_note_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, to="notes.tag"),
        ),
        migrations.RunPython(copiar_tag_para_tags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="note",
            name="tag",
        ),
    ]
